// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAvIyoR73JXSsEJwHHINJfzfPC-uu5eG4c',
    appId: '1:78563419795:web:35c679406fc1a695bccf66',
    messagingSenderId: '78563419795',
    projectId: 'trabalhoclonex',
    authDomain: 'trabalhoclonex.firebaseapp.com',
    storageBucket: 'trabalhoclonex.appspot.com',
    measurementId: 'G-272DLPMCWH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASh7S5vBJMGPnRDlF8MIDQPBXDZaT5B7U',
    appId: '1:78563419795:android:17d267d63eb03576bccf66',
    messagingSenderId: '78563419795',
    projectId: 'trabalhoclonex',
    storageBucket: 'trabalhoclonex.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA-nxawTe8ajxBhP4RmfDvBT9ttACd6KGo',
    appId: '1:78563419795:ios:cf96ad3ae13ebd46bccf66',
    messagingSenderId: '78563419795',
    projectId: 'trabalhoclonex',
    storageBucket: 'trabalhoclonex.appspot.com',
    iosBundleId: 'com.example.trabalhoapptwitter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD7AK98KTdOmDoipOW91yICrCKy760j_PQ',
    appId: '1:257452893974:ios:c5a0b0e211bd5e1a469237',
    messagingSenderId: '257452893974',
    projectId: 'trablhoapp-2a8c3',
    storageBucket: 'trablhoapp-2a8c3.appspot.com',
    iosBundleId: 'com.example.trabalho',
  );
}